- README.rst
Updated the readme with model examples that are less abstract. They reflect the django Model documentation making it easy for rookie django developers to grasp the concept.
https://docs.djangoproject.com/en/3.0/topics/db/models/
> Updated readme with models that are less abstract.

- .idea/misc.xml
- lib/iommi/base.py
- lib/iommi/form.py
- lib/iommi/query.py
- lib/iommi/table.py
- lib/iommi/templates/iommi/form/choice_select2.html
- tests/test_form_create_or_edit.py
- tests/test_forms.py
- tests/test_query.py
- tests/test_table.py
Make endpoints less of a special case. (e.g. collected into a Members and func beeing Refinable)
> Remove Field endpoint_handler special case

- README.rst
Eg. less technical, more "must have".
> Suggested description suiteable for a wider audience.

- .gitignore
- iommi/django_app.py
- iommi/fragment.py
- iommi/page__tests.py
- iommi/style_django_admin.py
- iommi/style_foundation.py
- iommi/style_semantic_ui.py
- iommi/style_water.py
- iommi/templates/iommi/base.html
- iommi/templates/iommi/base_bootstrap.html
- iommi/templates/iommi/base_django_admin.html
- iommi/templates/iommi/base_foundation.html
- iommi/templates/iommi/base_semantic_ui.html
- iommi/templates/iommi/base_test.html
- iommi/templates/iommi/base_water.html
Added blocks with useful hook points to add custom data in the templates.
> Cleaned up base templates.

- docs/howto.rst
Just some notes on things that took me longer to figure out than I would have liked...
> Minor doc improvements

- iommi/table.py
- iommi/table__tests.py
- tests/settings.py
Improved tests so we would discover regressions on this in the future
> Fixed date and time formatting

- .idea/iommi.iml
- examples/examples/.gitignore
- examples/examples/__init__.py
- examples/examples/form_examples.py
- examples/examples/menu_examples.py
- examples/examples/models.py
- examples/examples/page_examples.py
- examples/examples/settings.py
- examples/examples/supernaut.py
- examples/examples/table_examples.py
- examples/examples/urls.py
- examples/examples/views.py
- examples/locale/de/LC_MESSAGES/django.po
- examples/locale/sv/LC_MESSAGES/django.po
- examples/scrape_data.py
- iommi/__init__.py
Examples separated to different pages
> Cleanup of the example application

- iommi/style_bulma.py
Now at the right place and better named.  Simple patch to the bulma style to make use of the buttons class.
> Actions in bulma are called buttons

- iommi/table__tests.py
These tests fail.  For background see #90
> Tests to demonstrate the delete all bugs

- iommi/table__tests.py
This is just a quick testcase that really should have been part of #93
> Just a testcase so we don't have to run the example to see it working.

- iommi/query.py
Tests pass.  Comment in the code should explain it all...
> deepcopy is also evil.

- docs/howto.rst
An example would be good but I couldn't think of one with the existing sample data.
> A quick line on field validation. 

- iommi/style_bulma.py
- iommi/templates/iommi/form/bulma/field.html
> Fix error messages in forms in the bulma style to actually look like such

- iommi/query.py
- iommi/table.py
- iommi/table__tests.py
- iommi/templates/iommi/query/ajax_enhance.html
and they were slightly incorrect on non-bootstrap styles
> AJAX enhanced tables didn't work with multiple tables on a page

- examples/examples/form_examples.py
- iommi/django_app.py
- iommi/style_bulma.py
This also renames the bulma-horizontal style, to more honestly reflect the only thing it should be used for right now (and it makes it finally usable).
> Bulma layout improvements

- examples/examples/table_examples.py
- iommi/query.py
- iommi/style_base.py
- iommi/templates/iommi/query/advanced.html
- iommi/templates/iommi/query/ajax_enhance.html
- iommi/templates/iommi/query/form.html
(and by that Table.query.advanced.include=False is a thing)
> Make Query.advanced a Fragment 

- iommi/query.py
- iommi/table.py
for customizing querysets after applying filters
> add refinables: postprocess and filter

- iommi/form.py
- iommi/form__tests.py
This patch is intended to be merged after #139
> Further simplifications of field parsing code

- examples/examples/form_examples.py
- iommi/form.py
- iommi/form__tests.py
- iommi/table__tests.py
> Do not run form post_validation if we are in initial display mode

- examples/examples/form_examples.py
- iommi/form.py
- iommi/templates/iommi/form/form.html
So this just deals with nested forms as a way to compose complex forms by splitting functionality into several sub forms, and thereby possibly being able to reuse such sub forms across several different forms.
This also gives iommi something akin to https://docs.djangoproject.com/en/3.1/ref/forms/fields/#multivaluefield .
Unlike my previous announcements / previews it does *not* provide formsets yet.  Basically I haven't yet figured out how to do a combinator that creates a dynamic list of parts at bind time yet.  (Well I kinda did but the versions I have either make reinvoke angry or cause the "disturbance in the force error message", so not really).
But as per the example I think this is useful as is.
> Nested forms

- iommi/_db_compat.py
- iommi/table__tests.py
- tests/models.py
This is a failing new test case.   To demonstrate a bug I found but haven't yet had the time to fix.
> Testcase for auto generated model from textchoices

- iommi/form.py
- iommi/form__tests.py
...and Editable on a form should be evaluated
> Evaluate parameters should contain instance

- iommi/form__tests.py
- iommi/member.py
- iommi/table__tests.py
Use attr=... and give another name
> Deprecate names with __ in names

- iommi/_db_compat.py
- iommi/form.py
- iommi/form__tests.py
Also set default on many-to-many to required=False
Issue #201
> Fix enforcement on required=True on multi_choice

- iommi/table.py
- iommi/table__tests.py
You can now add html after or before the rows from the table itself.
> Improved ability to customize Table.tbody.

- iommi/form__tests.py
- iommi/style_base.py
- iommi/templates/iommi/form/choice_select2.html
If you dynamically modify with javascript you can call `iommi_init_all_select2` to re-initialize iommi select2 components.
> Re-initializable select2 enhancement.

- iommi/form__tests.py
- iommi/member.py
- iommi/member__tests.py
- iommi/refinable.py
- iommi/refinable__tests.py
- iommi/table__tests.py
> Fix missing check that call_target is not possible to change

- iommi/table.py
- iommi/table__tests.py
It was broken if you did multiple bind() on the same object
> Fix auto rowspan

- Makefile
- README.rst
- docs/README.rst
- iommi/declarative/namespace.py
- iommi/declarative/namespace__tests.py
- iommi/endpoint.py
- iommi/fragment.py
- iommi/refinable.py
I started reading through part of iommi's codebase in order to familiarise myself with how it works internally. During this process I sometimes stumbled over things that weren't immediately clear to me. This PR contains a number of minor tweaks to improve readability based on this experience. The commit messages should give enough context for the reason behind a suggested change (in case it isn't obvious anyway).
The only addition that I'm not entirely certain about is the docstring for the `Prio` enum in `refinable.py`. Is this an accurate reflection of this class's purpose?
I hope this is useful. Please let me know what you think. Many thanks!
> Readability tweaks

- iommi/form.py
- iommi/form__tests.py
- tests/models.py
> forms: check model.validate_constraints() on django 4.1+

- iommi/form.py
- iommi/traversable.py
> Next major: Include all parameters in Field.is_valid callback

- iommi/form.py
- iommi/form__tests.py
> Fix EmailField / URLField required=False

- iommi/form.py
- iommi/form__tests.py
> parse_empty_string_as_none not working properly with choice

- docs/test_doc_cookbook_queries.py
> Added example to the docs->cookbook->queries->"How do I control what Q is produced?"

- iommi/static/js/iommi.js
- fixed select2 reset in filter form
- improved IommiSelect2
- added missing semicolons
> iommi.js fixed/improved

- docs/test_doc_cookbook_forms.py
- iommi/form.py
- iommi/form__tests.py
> Form.fields_template

- iommi/base.py
- iommi/table.py
> lazy capitalize

- iommi/form.py
- iommi/form__tests.py
- iommi/query.py
- iommi/query__tests.py
- iommi/table.py
- iommi/table__tests.py
> Datetime localtime

- iommi/part.py
uuids where not correctly jsonized, therefore select field with uuid as pk would not work, this change should fix this
> fix(part): change json serializer to djangos own

- iommi/form.py
> Fixed models.CharField(choices=..., blank=True, null=False) validation

- iommi/static/js/iommi.js
I moved the code from `updateURL` to `queryPopulate`, because it's not used anywhere else and it would need a new parameter (probably `form`), so it would be also inconsistent with the old `iommi_update_URL`.
So now both `iommi_update_URL` and `updateURL` are deprecated. I would still leave them for some time, just to be sure.
And please if you can test it first before merging? The main problem in steps was:
1. you sort a table
2. you filter by something
-> `order` got removed from the URL query string and thus the table wasn't in the right order anymore
+ also if you had multiple tables on a page, one filter would remove other filters from the URL query string
> preserving filters from other table filters and sorting

- docs/test_doc_tables.py
- iommi/table.py
- iommi/table__tests.py
> added option to pass kwargs for csv.writer

- iommi/form.py
- iommi/form__tests.py
- tests/models.py
> Field.is_valid() taking model field validators by default

- iommi/style__tests.py
- iommi/style_bootstrap_icons.py
- iommi/style_font_awesome_4.py
- iommi/table.py
- tests/helpers.py
> table.Column.boolean check mark

- iommi/table__tests.py
> default_sort_order indication test

- iommi/locale/zh_Hans/LC_MESSAGES/django.po
Edit is translated as Delete in Chinese. This commit fix it.
> translate: fix Edit in chinese

- iommi/form.py
- iommi/form__tests.py
> Allow throwing str and Template into Form.fields

- iommi/table.py
- iommi/table__tests.py
To not make e.g. .annotate in postprocess_rows trip up
> Fix empty QuerySet on invalid Query

- iommi/form.py
- iommi/form__tests.py
> Required as a lambda on a `Field` was broken

- iommi/_db_compat.py
- iommi/table__tests.py
- tests/models.py
> Support IntegerField with choices

- iommi/static/js/iommi.js
- iommi/templates/iommi/query/form.html
can you pls test the `iommi.js` first?
> Fix js global errors

- iommi/static/css/iommi.css
- iommi/style_base.py
- iommi/table.py
- iommi/templates/iommi/query/form.html
- iommi/traversable__tests.py
1) js for advanced filter only when advanced filter included
2) css for query and advanced filter moved to `static/css/iommi.css`
for now I'd put the `assets__iommi_css` only in query assets, if later needed it can be moved to root assets
> Advanced filter js css

- iommi/debug__tests.py
- iommi/endpoint__tests.py
- iommi/member__tests.py
- iommi/part.py
- iommi/style__tests.py
- iommi/style_test_base.py
- iommi/traversable.py
- iommi/traversable__tests.py
Having declarative declarations not handled by on_refine_done made for some strange error conditions
> Move declarations of assets and endpoints from Traversable down to Part

- iommi/edit_table.py
> Fix: show new rows when errors occur in other nested forms with nesed_forms_abort_save_on_fail=True

- iommi/edit_table.py
- iommi/edit_table__tests.py
btw notice
`<ul><li>This field is required</li></ul>` in Form
vs
```
<span class="text-danger">
<ul class="errors">
<li>This field is required</li>
</ul>
</span>
```
in EditTable
is that on purpose?
> improved previous fix of abort_on_fail + tests

- iommi/form.py
- iommi/form__tests.py
plus allow `redirect_to` as a callable
> use create_or_edit_object_redirect in save_nested_forms
