iommi/datetime_parsing.py, iommi/datetime_parsing__tests.py, iommi/form.py, iommi/form__tests.py, iommi/query.py, iommi/query__tests.py, iommi/templates/iommi/query/form.html, test_requirements.txt
Suppport more time formats
Introduced Filter.parse() which is a hook point for handling special parsing in the query language
The query language will no longer try to convert to integers, floats and dates for you. You have to specify a parse() method. This also makes the query language much more flexible.
=> Support relative dates/datetimes

iommi/style_bulma.py
Exactly what is says on the tin.  The active menu item should be marked by class is-active and not active.
=> active is spelled is-active in bulma

docs/howto.rst, examples/examples/views.py, iommi/form.py, iommi/style_base.py
(Most modern browsers but Safari on Mac OS support it).  And even Safari degrades gracefully to a text control.  And the existing date implementation already does the right thing (convert to and fro ISO format).
=> Render date fields as such (

examples/examples/views.py, iommi/form.py, iommi/templates/iommi/form/choice.html
What it says on the tin.  I chose not to support django forms API (where the choices are interpreted differently if the values are lists or tuples), even so it leads to pretty callsites. 
In practice I found the proposed API more eh practical ;-)
Existing test cases pass and the adjusted form kitchen sink does what you expect.
BUT note the comment on the existing choice_tuples method.
=> Support for optgroups

iommi/action.py, iommi/form.py, iommi/style_bootstrap.py, iommi/style_bulma.py, iommi/style_foundation.py, iommi/style_semantic_ui.py, iommi/table.py
This is similar to the already existing Action.delete. Form's standard button is now primary.  But the button used on a table's query form is not, on the assumption that on many pages that will not be the default action.  If we had a standard Action.info or similar I would have used that -- maybe another day.
=> Differentiate between primary and other actions

MANIFEST.in
I finally figured out why my app wasn't localized properly... The iommi package didn't include the locale.
=> Include locale info in the package

iommi/query.py, iommi/query__tests.py
It always returned empty querysets and didn't produce errors when you tried to do stuff like my_boolean<3.
=> Filtering on booleans was very broken. 

iommi/query.py, iommi/table__tests.py
I haven't investigated the cause.
=> Tests to demo a bug.

iommi/table.py, iommi/table__tests.py
Idea: Introduce separate fields for the different stages (initial rows, sorted rows, filtered rows, visible rows).
Why is that good?  Because it means we bind / set each field once and the semantics does not depend on where we are in the life-cycle of the table object (mutation is evil).
Indeed I ended up writing this patch because I had a bug trying to write a different patch, which happened because
I hadn't realized that self.paginator is used to rewrite self.rows to be just the visible rows.
As much as table.rows is considered to be a public API it changes the API (see the change in one of the tests).  Now
it didn't seem to have a clearly documented semantics so maybe this is fine.  At the moment I also haven't documented
the new fields.  Which is fine as long as table is primarily …
=> Make table.rows do one thing and introduce new names for the other things.

iommi/table.py, iommi/table__tests.py, tests/models.py
Still broken for the case of injecting more config for those fields/columns/filters.
=> Fixed basic case of auto__model dunder paths broken.

examples/examples/table_examples.py, iommi/table.py, iommi/table__tests.py, iommi/templates/iommi/table/js_select_all.html
Support select on lists (and custom bulk_actions in the presense of those).
To that end there is a new function `table.selection()` which returns the selected rows as either a `queryset` or a `list` according to the type of `rows`.
`bulk_queryset` is now implemented in terms of `selection` and does the filtering according to `bulk_filter` and `bulk_exclude`.
There is a new example to showcase the functionality.
=> Select on lists

examples/examples/table_examples.py, iommi/query.py
Query forms can now have additional fields, that are ignored by the filter handling code (when you want to do additional filtering outside of the query logic).
=> Additional fields in query forms

iommi/admin.py, iommi/error.py, iommi/error__tests.py, iommi/form.py, iommi/form__tests.py
This makes the set of errors be `_errors`, while `errors` is now an instance of `Errors` that is used for rendering and not adding errors. To add an error to a `Field` or `Form` use the `add_error` methods
=> Cleanup of how errors are handled

iommi/table.py, iommi/table__tests.py
If you want to not render a column but still want the filters, use the render_column=False feature.
=> include=False on a Column should imply not generating the query filter and bulk field

iommi/form.py, iommi/form__tests.py
On multiselect choice (and choice_queryset) the choice_to_option implementation returns the value [] (and not True/False) as third in the choice_to_option tuple. For code using javascript idea "truthiness" to select what to render this leads to a lot of misstakenly rendered options... This should always be True or False
Also, there is no need to have different choice_to_option any more when in the multi-case, so with a little cleanup any choice dericative can be done multiple by adding `is_list=True` now.
=> Broken multiselect on empty list

iommi/query.py, iommi/templates/iommi/query/ajax_enhance.html
That way we don't rely on class names that are determined by the active style.
=> Fix the bug introduced in #112 by giving the form filter button a distinct class name.

iommi/form.py
This feature in itself is pretty trivial.  It does two things.  Change the implementation of Field.form to the implementation @jlubcke  suggested in discord.  And also it fixed a bunch of existing places inside Field to actually use Field.form in the first place.
The testcases pass and form/all_fields/ of the examples works.
Note I do not yet claim that we can actually start nesting fields inside other elements and everything will work.  I just wanted to prepare the land so to speak...
=> Start to uncouple form's and their fields

iommi/form.py
`Form.is_valid` delayed computing validity until `is_valid` was called for the first time. And then it would call `validate` and also check if any of the fields had errors to set `_valid`.  BUT 
1. we always called `is_valid` at the end of `on_bind`, so we might as well just call `validate` directly 
2. Both `Field`'s and `Form`'s `add_error` would set `form._valid = False` if they were called, so there is no need to recurse and check `field.errors` explicitly.
So do away with most of that, which I suspect were leftovers from before the recent Errors overhaul. 
And also add some comments ;-)
The tests pass, and cursory checking of the examples revealed no problems either.
=> Simplify is_valid.

iommi/debug.py, iommi/debug__tests.py, iommi/fragment.py, iommi/page.py, iommi/part.py, iommi/style.py, iommi/style__tests.py, iommi/style_base.py, iommi/style_bootstrap.py, iommi/style_bulma.py, iommi/style_django_admin.py, iommi/style_font_awesome_4.py, iommi/style_foundation.py, iommi/style_semantic_ui.py, iommi/style_test_base.py, iommi/style_water.py
Convert the specifics of the assets styling to be a general add-style-to-root feature
Use new root styling for adding the debug tree endpoint.
Convert top level asset styling to use the new root feature.
=> Styling on root

iommi/form.py, iommi/form__tests.py
Given that always only one of both should be "active" it seemed simpler this way.
=> Collapse raw data and raw data list

iommi/reinvokable.py, iommi/reinvokable__tests.py, iommi/style.py, iommi/style__tests.py, iommi/table__tests.py
Fix reinvoke/reinvoke_new_defaults to not just drop updated shortcut targets
=> Fix reinvoke/reinvoke_new_defaults when shortcut is changed

examples/examples/form_examples.py, iommi/action.py, iommi/form.py, iommi/form__tests.py
But still allow the same concise definitions of the submit button as we did before.  How?  If there is something in actions__submit we by default assume it is a primary button.
As you have to define a post_handler to get anything meaningful anyway this should be silent to real clients.  The hopefully only place where this caused real breakage was some of our tests, as we lazily tend to only specify in the test what is strictly needed to get the test to run.
=> No longer create a submit button by default.

iommi/table.py, iommi/table__tests.py, iommi/templates/iommi/table/select_column_header.html, tests/models.py
This is to avoid to invoke (potentially expensive) .count() on the rows
of the table.
Still somewhat broken and maybe other thins should be parts.
Also make_select_display_name is a party-pooper forcing eval all the time...
=> Make Paginator a proper lazy Part of Table.

iommi/debug.py, iommi/menu.py, iommi/menu__tests.py, iommi/style.py
The DebugMenu is the only import level code that triggers the collect_members/bind_members machinery.
Making this only evaluated when needed makes for far fewer unintended breakpoints in the debugger when refactoring the internals.
=> Make DebugMenu created on demand to avoid setting of breakpoints

iommi/query.py, iommi/query__tests.py
Always using the .pk fallback approach always is more stable when the search field values might not be unique
=> Avoid using search_fields when composing queries from model filter values

iommi/templates/iommi/query/advanced.html
Right now, the help text is a bit annoying to look at as the examples of code to paste don't really pop out.
**I have not tested this**, but the included bootstrap should automatically format these into styled inline code blocks which should enforce a slightly different element background, text colour, and change the font to something monospaced.
=> Add code tags to examples in query help

iommi/table.py, iommi/table__tests.py
After the rows field cleanup the paginator was no longer lazily bound.
The problem with that is that it gives an invokation of the rows query
to count the number of lines, and that can be expensive. The visible
rows calculation should be delayed until it is actually needed.
=> Fix issue with ajax loading binding the paginator

iommi/form.py, iommi/form__tests.py
This became the default behavior for `.as_view()` in iommi 4.1 so that release is broken.
=> Validation could be bypassed for forms if they have been saved via `form.refine_done()`

README.rst, docs/README.py, docs/README.rst, docs/test_doc_styles.py, iommi/apps.py, iommi/style_bootstrap5.py, iommi/style_bootstrap_icons.py
Fairly minimal bootstrap5 style module - very like the bootstrap4 one...
One issue I am aware of is that a `select` tag should have a class of `form-select` but instead gets a `form-control` class
becuase I was unable to work out how to pick out that particular tag/input type.
This could be fixed in CSS, or actually appears to be OK despite it not being styles as per the Bootstrap docs (howver in
some cases the select/dropdown appears to lose its dropdown caret marking).
Additionally bootstrap-icons are packaged in the same way as font-awesome.
=> Basic Bootstrap5 Style

iommi/form.py, iommi/form__tests.py, iommi/style_base.py, iommi/style_bootstrap.py, iommi/style_bootstrap5.py, iommi/templates/iommi/form/bootstrap/row_checkbox.html, iommi/templates/iommi/form/row_checkbox.html
This also removes the checkbox template for base and bootstrap styles, which is a nice little cleanup.
=> Fixed rendering of disabled checkbox

iommi/form.py, iommi/form__tests.py, tests/urls.py
Currently it is not possible to use `redirect_to` with `reverse_lazy`. For example, the following fails:
```python
Form.create(
auto__model=Album,
extra__redirect_to=reverse_lazy("album-list")
)
```
This is because `reverse_lazy` returns a string _proxy_ (an instance of `django.utils.functional.Promise`), so the [type check](https://github.com/TriOptima/iommi/blob/master/iommi/form.py#L1244) in `create_or_edit_object_redirect` fails.
This PR allows the value of `redirect_to` to be a `Promise` for a string so that the above snippet works as expected.
I haven't had time to write a test yet, but I assume one should be added in `form__tests.py`?
=> Enable usage of 'reverse_lazy' with 'redirect_to'

iommi/style.py, iommi/style__tests.py
Fixes the documentation issue in #293
=> Warn for non-capital class names in style definition

iommi/from_model.py, iommi/query__tests.py, iommi/table__tests.py, tests/models.py
Fixes a regression introduced in 5.8.0.
Given an example:
```python3
class Parent(Model):
name = CharField(max_length=255)
class Child(Model):
parent = OneToOneField(Parent, on_delete=CASCADE)
myfield = CharField(max_length=255)
```
Before 5.8.0, the dunder path to access the `Child.myfield` from `Parent` in a Table was consistent with Django's behavior (`Parent.child` contains the corresponding `Child` instance):
```python3
Table(auto__model=Parent, auto__include=["name", "child__myfield"])
```
Since 5.8.0, the above table raises an AssertioError `You can only include fields that exist on the model`. In 5.8.0, the dunder path to the field changed to `child_set__myfield`, which is inconsistent with how the object is accessed on the model class in Django.
This commit brings back the …
=> dunder field lookups for reverse 1-to-1 relationship: drop _set suffix

iommi/static/js/iommi.js
because `reset` event is being called just before the values get reset
plus safer way of getting container in enhanceFilterForm
=> fixed filter form reset

iommi/__init__.py, iommi/__init__tests.py
The previous iommi middleware implementation would raise an error if any database connection had ATOMIC_REQUESTS enabled.
This commit changes the middleware to use transaction savepoints instead, so atomicity is retained while still allowing iommi to intercept and render responses.
**Changes:**
- Updated middleware logic to preserve atomicity if enabled in database settings
- Ensured proper rollback in the event of exceptions
I added tests to ensure that the transactions are working as expected.
=> Added atomic support to middleware

iommi/struct.py, iommi/struct__tests.py
Item access should have dict behavior on missing keys
=> Fix over-optimized Struct semantics

iommi/table.py
if you had in url `?order=` without value, you got IndexError(string index out of range)
=> fix empty order

iommi/profiling.py
function_name can be formatted as `<built-in method builtins.len>`, so it needs to be escaped; otherwise, the function name won't display at all in the resulting HTML. For extra clarity, function name is only rendered as a link if it's associated with a path and line number.
Before image:
After image:
=> Escape function name in profiler

iommi/static/js/iommi.js
select2 change triggers form change, but field can be outside a form for js purpose
=> JS error when select2 is outside form

.pre-commit-config.yaml, iommi/edit_table__tests.py, iommi/static/js/iommi.js, iommi/style__tests.py, iommi/table.py, iommi/table__tests.py
This is to avoid them being over-written by any empty_message provided resulting in no table tag being rendered
=> Move the data-endpoint and data-iommi-id html attributes to the table container

iommi/form.py, iommi/form__tests.py, iommi/style_base.py
non-editable textarea now `disabled` instead of `readonly`
=> non_editable_input attrs__disabled moved to base style + added textarea

iommi/table.py, iommi/table__tests.py
Currently when selecting all items on all pages is and running a bulk action it only works if that table is the first table in an iommi page. If its the second table it will silently ignore the instruction and just do it on the items you actually selected.
=> Fix bulk 'all items on all pages' with multiple tables

iommi/edit_table.py, iommi/table.py
This would remove styling from `Cell`, but it's quite a bit faster.  At Dryft I have a (admittedly way too big) page that goes from ~4s to ~3.6s with this change.
=> Transient `Cell` refactor

docs/test_doc_forms.py, iommi/form.py, iommi/form__tests.py
I named it `model_object`, because in `Form.own_evaluate_parameters` there is already `instance=self.instance`
=> support overriding model_object.save() to be able to pass kwargs
